// import React from "react";

export default function CSenergy() {
  return (
    <div>
      <h3>Energy</h3>
      <input
        type="checkbox"
        className="energy-checkbox"
        name="energy"
        value="0"
      />
      <input
        type="checkbox"
        className="energy-checkbox"
        name="energy"
        value="1"
      />
      <input
        type="checkbox"
        className="energy-checkbox"
        name="energy"
        value="2"
      />
      <input
        type="checkbox"
        className="energy-checkbox"
        name="energy"
        value="3"
      />
      <input
        type="checkbox"
        className="energy-checkbox"
        name="energy"
        value="4"
      />
      <input
        type="checkbox"
        className="energy-checkbox"
        name="energy"
        value="5"
      />
      <input
        type="checkbox"
        className="energy-checkbox"
        name="energy"
        value="6"
      />
      <input
        type="checkbox"
        className="energy-checkbox"
        name="energy"
        value="7"
      />
    </div>
  );
}
